spring:
  application:
    name: auth-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      client-id: 1
    passenger-create-topic: "passenger-create-topic"
    driver-create-topic: "driver-create-topic"
keycloak:
  auth-server-url: http://localhost:8180
  realm: agregator-app
  client-id: backend
  client-secret: ${CLIENT_SECRET}
  admin-username: ${ADMIN_USERNAME}
  admin-password: ${ADMIN_PASSWORD}
server:
  port: 8087