spring:
  application:
    name: auth-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      client-id: 1
    passenger-create-topic: "passenger-create-topic"
    driver-create-topic: "driver-create-topic"
keycloak:
  auth-server-url: http://localhost:8180
  passenger-realm: agregator-app
  driver-realm: driver-realm
  passenger-client-id: backend
  driver-client-id: driver-client
  passenger-client-secret: VCvbgWVouac0TomlMIeQxo2rafxmX74j
  driver-client-secret: ayMgwzH3nWwTld4t2thkSgtJTW3EqdfL
  admin-username: admin
  admin-password: admin
server:
  port: 8087