services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
  liquibase-migrations-passenger:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/passenger_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./passenger-service/migrations:/liquibase/changelog
  liquibase-migrations-driver:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/driver_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./driver-service/migrations:/liquibase/changelog
  liquibase-migrations-rides:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/rides_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./rides-service/migrations:/liquibase/changelog
  liquibase-migrations-reviews:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/review_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./review-service/migrations:/liquibase/changelog
  liquibase-migrations-wallets:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/wallet_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./wallet-service/migrations:/liquibase/changelog
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    restart: on-failure
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
  artemis-mq:
    image: apache/activemq-artemis:latest-alpine
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      ANONYMOUS_LOGIN: true