services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
    - ./db-init:/docker-entrypoint-initdb.d
  liquibase-migrations-passenger:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/passenger_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./passenger-service/migrations:/liquibase/changelog
  liquibase-migrations-driver:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/driver_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./driver-service/migrations:/liquibase/changelog
  liquibase-migrations-rides:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/rides_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./rides-service/migrations:/liquibase/changelog
  liquibase-migrations-reviews:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/review_service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./review-service/migrations:/liquibase/changelog