services:
  postgresql:
    image: postgres:16
    environment:
      POSTGRES_DB: passenger-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgresql
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5432/passenger-service
      - --username=postgres
      - --password=root
      - update
    volumes:
      - ./migrations:/liquibase/changelog