spring:
  application:
    name: rides-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/rides_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  liquibase:
    enabled: false
server:
  port: ${PORT:8085}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  name:
    passenger: PASSENGER-SERVICE
    driver: DRIVER-SERVICE
    review: REVIEW-SERVICE
    wallet: WALLET-SERVICE