spring:
  application:
    name: rides-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/rides_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  liquibase:
    enabled: false
server:
  port: ${PORT:8085}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
feign:
  name:
    passenger: PASSENGER-SERVICE
    driver: DRIVER-SERVICE
    review: REVIEW-SERVICE
    wallet: WALLET-SERVICE
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans