spring:
  application:
    name: rides-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false
server:
  port: ${PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  name:
    passenger: PASSENGER-SERVICE
    driver: DRIVER-SERVICE
    review: REVIEW-SERVICE
    wallet: WALLET-SERVICE