spring:
  application:
    name: rides-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/}rides_service
    username: postgres
    password: root
  liquibase:
    enabled: false
server:
  port: ${PORT:8085}
