spring:
  application:
    name: rides-service
  datasource:
    url: jdbc:postgresql://localhost:5433/rides_service
    username: postgres
    password: root
  liquibase:
    enabled: false
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
