spring:
  application:
    name: wallet-service
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5433/wallet_service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: 8084