spring:
  application:
    name: wallet-service
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/}wallet_service
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: ${PORT:8086}
feign:
  passenger_name: passenger-feign-client
  driver_name: driver-feign-client
  url:
    passenger: localhost:8082/api/v1/passengers
    driver: localhost:8083/api/v1/drivers