spring:
  application:
    name: wallet-service
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/wallet_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/agregator-app
          jwk-set-uri: http://localhost:8180/realms/agregator-app/protocol/openid-connect/certs
server:
  port: ${PORT:8086}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
feign:
  name:
    passenger: PASSENGER-SERVICE
    driver: DRIVER-SERVICE
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  file:
    path: /Users/qooriq/IdeaProjects/aggregator-app/monitoring/logs