spring:
  application:
    name: wallet-service
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/wallet_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: ${PORT:8086}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
feign:
  name:
    passenger: PASSENGER-SERVICE
    driver: DRIVER-SERVICE