spring:
  application:
    name: wallet-service
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL}
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
server:
  port: ${PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  name:
    passenger: PASSENGER-SERVICE
    driver: DRIVER-SERVICE