spring:
  application:
    name: gateway-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/agregator-app
          jwk-set-uri: http://localhost:8180/realms/agregator-app/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
server:
  port: ${PORT:8081}