spring:
  application:
    name: gateway-service
  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  management:
    endpoints:
      web:
        exposure:
          include: health,prometheus
    metrics:
      distribution:
        percentiles-histogram:
          "[http.server.requests]": true
    prometheus:
      metrics:
        export:
          enabled: true
server:
  port: ${PORT:8080}