spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5433/driver_service
    password: root
    username: postgres
  liquibase:
    enabled: false
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: admin
    password: admin
    mode: native
server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
