spring:
  application:
    name: driver-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/driver_service}
    password: ${DB_USERNAME:postgres}
    username: ${DB_PASSWORD:root}
  liquibase:
    enabled: false
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USERNAME:admin}
    password: ${ARTEMIS_PASSWORD:admin}
    mode: native
  data:
    jdbc:
      dialect: postgresql
server:
  port: ${PORT:8083}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}