spring:
  application:
    name: driver-service
  datasource:
    url: ${DB_URL}
    password: ${DB_USERNAME}
    username: ${DB_PASSWORD}
  liquibase:
    enabled: false
  artemis:
    broker-url: ${ARTEMIS_URL}
    user: ${ARTEMIS_USERNAME}
    password: ${ARTEMIS_PASSWORD}
    mode: native
  data:
    jdbc:
      dialect: postgresql
server:
  port: ${PORT}