spring:
  application:
    name: driver-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/driver_service}
    password: ${DB_PASSWORD:root}
    username: ${DB_USERNAME:postgres}
  liquibase:
    enabled: false
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: ${ARTEMIS_USERNAME:admin}
    password: ${ARTEMIS_PASSWORD:admin}
    mode: native
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      client-id: 1
  data:
    jdbc:
      dialect: postgresql
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/agregator-app
          jwk-set-uri: http://localhost:8180/realms/agregator-app/protocol/openid-connect/certs
server:
  port: ${PORT:8083}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: b3
      produce: b3
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans