spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5433/driver_service
    password: root
    username: postgres
  liquibase:
    enabled: false
  artemis:
    broker-url: ${ARTEMIS_URL:tcp://localhost:61616}
    user: admin
    password: admin
    mode: native
logging:
  level:
    org.springframework.jms.listener: TRACE
    org.apache.activemq.artemis.core.client: DEBUG
    org.apache.activemq.artemis.jms.client: DEBUG
server:
  port: 8083
