global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://host.docker.internal:8761/eureka'
#      - server: 'http://eureka-server:8761/eureka'
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: job