spring:
  application:
    name: passenger-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/}passenger_service
    username: postgres
    password: root
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: passenger-group
    properties:
      security.protocol: PLAINTEXT
passenger-service:
  topic-name-passenger: passenger-review-update
  kafka:
    partitions: 3
    replicas: 1
server:
  port: ${PORT:8082}