spring:
  application:
    name: passenger-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/passenger_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    consumer:
      group-id: passenger-group
    properties:
      security.protocol: PLAINTEXT
passenger-service:
  topic-name-passenger: passenger-review-update
  kafka:
    partitions: 3
    replicas: 1
  resilience4j:
    failure-rate: 50
    duration-in-open-state: 10000
    sliding-window-size: 10
server:
  port: ${PORT:8082}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/