spring:
  application:
    name: passenger-service
  datasource:
    url: jdbc:postgresql://localhost:5433/passenger-service
    username: postgres
    password: root
  liquibase:
    enabled: false
passenger-rating:
  limit: 50
  page-number: 0
server:
  port: 8082
