spring:
  application:
    name: passenger-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      group-id: passenger-group
    properties:
      security.protocol: PLAINTEXT
passenger-service:
  topic-name-passenger: passenger-review-update
  kafka:
    partitions: 3
    replicas: 1
  resilience4j:
    failure-rate: 50
    duration-in-open-state: 10000
    sliding-window-size: 10
server:
  port: ${PORT}