spring:
  application:
    name: review-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      client-id: 1
  artemis:
    broker-url: ${ARTEMIS_URL}
    user: ${ARTEMIS_USERNAME}
    password: ${ARTEMIS_PASSWORD}
    mode: native
passenger-rating:
  limit: 50
  page-number: 0
app:
  kafka-config-info:
    topic-name-passenger: passenger-review-update
    replicas: 1
    partitions: 3
  chrono-update: 0 * * * * ?
  page: 1
  size: 10
server:
  port: ${PORT}
feign:
  passenger_name: passenger-feign-client
  driver_name: driver-feign-client
  ride_name: ride-feign-client
  url:
    passenger: localhost:8082/api/v1/passengers
    driver: localhost:8083/api/v1/drivers
    ride: localhost:8085/api/v1/rides