spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5433/review_service
    username: postgres
    password: root
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: 1
  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    mode: native
passenger-rating:
  limit: 50
  page-number: 0
app:
  kafka-config-info:
    topic-name-passenger: passenger-review-update
    replicas: 1
    partitions: 3
  chrono-update: 0 * * * * ?
  page: 1
  size: 10
server:
  port: 8084
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  passenger_name: passenger-feign-client
  driver_name: driver-feign-client
  ride_name: ride-feign-client
  url:
    passenger: localhost:8082/api/v1/passengers
    driver: localhost:8083/api/v1/drivers
    ride: localhost:8085/api/v1/rides