spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://localhost:5433/review_service
    username: postgres
    password: root
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      client-id: 1
  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    mode: native
passenger-rating:
  limit: 50
  page-number: 0
review-service:
  kafka:
    topic-name-passenger: passenger-review-update
    topic-name-driver: driver-review-update
    replicas: 1
    partitions: 3
server:
  port: 8083