spring:
  application:
    name: review-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    consumer:
      client-id: 1
  artemis:
    broker-url: ${ARTEMIS_URL}
    user: ${ARTEMIS_USERNAME}
    password: ${ARTEMIS_PASSWORD}
    mode: native
passenger-rating:
  limit: 50
  page-number: 0
app:
  kafka-config-info:
    topic-name-passenger: passenger-review-update
    replicas: 1
    partitions: 3
  chrono-update: 0 * * * * ?
  page: 1
  size: 10
server:
  port: ${PORT}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  name:
    passenger: PASSENGER-SERVICE
    driver: DRIVER-SERVICE
    ride: RIDES-SERVICE